/**
 * Maps practice problem names to module files and exported symbols.
 */
export const problemMap = {
  'Create a Sampling function': ['core-functional.js', 'sample'],
  'Create a toggle function': ['core-functional.js', 'toggle'],
  'Flatten an Array': ['core-functional.js', 'flattenArray'],
  'Piping-1': ['core-functional.js', 'pipe'],
  'Piping-2': ['core-functional.js', 'pipe2'],
  'Method chaining': ['core-functional.js', 'Calculator'],
  Currying: ['core-functional.js', 'curry'],

  'Publisher-Subscriber': ['timing-events-sdk.js', 'EventBus'],
  'Publisher-subscriber 2': ['timing-events-sdk.js', 'EventBus2'],
  Debouncing: ['timing-events-sdk.js', 'debounce'],
  Throttling: ['timing-events-sdk.js', 'throttle'],
  'Implement clearAllTimeout': ['timing-events-sdk.js', 'createTimeoutManager'],
  'Create an analytics SDK': ['timing-events-sdk.js', 'AnalyticsSDK'],
  'Implement an router middleware': ['timing-events-sdk.js', 'createApp'],
  'Check performance of async and sync functions': ['timing-events-sdk.js', 'benchmarkSync / benchmarkAsync'],

  'Memoize a function': ['polyfills-promises.js', 'memoize'],
  'Polyfill for Array.filter': ['polyfills-promises.js', 'installArrayFilterPolyfill'],
  'Polyfill for Array.map': ['polyfills-promises.js', 'installArrayMapPolyfill'],
  'groupBy() polyfill': ['polyfills-promises.js', 'groupBy'],
  'Implement an Array iterator method': ['polyfills-promises.js', 'arrayIterator'],
  'Promise.all() polyfill': ['polyfills-promises.js', 'promiseAll'],
  'Promise.any() polyfill': ['polyfills-promises.js', 'promiseAny'],
  'Sum up functions return value running in parallel and in sequence': ['polyfills-promises.js', 'sumParallel / sumSequence'],

  'Remove cycle from the object': ['object-transform.js', 'removeCycle'],
  'Convert HEX color to RGB': ['object-transform.js', 'hexToRgb'],
  'Get object value from string path': ['object-transform.js', 'getByPath'],
  'Filter nested object': ['object-transform.js', 'filterNestedObject'],
  'Flatten a deeply nested object using dot notation': ['object-transform.js', 'flattenObjectDot'],

  'Create composeAsync function with chaining support': ['async-concurrency.js', 'composeAsync'],
  'Implement mapLimit async function': ['async-concurrency.js', 'mapLimit'],
  'Process async callbacks queue': ['async-concurrency.js', 'AsyncQueue'],

  'Create a School using OOPs principle': ['oop-models.js', 'School / Student / Teacher'],

  'Longest Consecutive Sequence': ['dsa.js', 'longestConsecutive'],
  'Number of subarrays with given sum k': ['dsa.js', 'subarraySum'],
  'Reverse last k elements in a queue': ['dsa.js', 'reverseLastK'],
  'Implement browser history': ['dsa.js', 'BrowserHistory'],
  'Sort string based frequency of characters': ['dsa.js', 'frequencySort'],
  'Caesar Cipher': ['dsa.js', 'caesarCipher'],
  'Sorting a linked list': ['dsa.js', 'sortLinkedList'],
  'Filter array of objects on value or index': ['dsa.js', 'filterObjects'],
  'Implement two stack with an array': ['dsa.js', 'TwoStacks'],
  'Detect overlapping circles': ['dsa.js', 'isOverlappingCircle'],
  'Trapping rain water': ['dsa.js', 'trapRainWater'],
  'Tic-Tac-Toe': ['dsa.js', 'TicTacToe'],
  'Implement deque data structure': ['dsa.js', 'Deque'],
  'Find digital root of a number': ['dsa.js', 'digitalRoot'],
  'Find highest commodity price under a timestamp': ['dsa.js', 'maxPriceUntil'],
  'Text Justification': ['dsa.js', 'fullJustify'],
  'Iterate N-array nested list': ['dsa.js', 'iterateNested'],

  'Capture product visible on viewport when user stops scrolling - Vanilla Js': ['frontend-dom.js', 'setupVisibleProductsTracker'],
  'Image comparison slider': ['frontend-dom.js', 'setupImageComparisonSlider'],
  'Responsive slideshow gallery': ['frontend-dom.js', 'createSlideshow'],
  'Create a lightbox (Modal-Image-gallery)': ['frontend-dom.js', 'createLightbox'],
  'Animate elements in sequence': ['frontend-dom.js', 'animateInOrder'],
  'Preview zoomed image on Hover': ['frontend-dom.js', 'setupZoomPreview'],
  'Preview selected color from swatches': ['frontend-dom.js', 'setupColorSwatches'],

  'Create Multi-Stepper component in React': ['react-patterns.js', 'Stepper'],
  'Capture product visible on viewport when user stops scrolling - Reactjs': ['react-patterns.js', 'ProductVisibilityTracker'],
  'Editable todo list in React': ['react-patterns.js', 'EditableTodoList'],
  'Functional Modal Component': ['react-patterns.js', 'Modal'],
  'Search with Autocomplete in React': ['react-patterns.js', 'AutoComplete'],
  'Image auto carousel in React': ['react-patterns.js', 'AutoCarousel'],
  'Create scroll indicator in react': ['react-patterns.js', 'ScrollIndicator'],
  'Pagination component': ['react-patterns.js', 'getPaginationModel'],
  'Create usePrevious() hook': ['react-patterns.js', 'usePrevious'],
  'usePageVisits() hook': ['react-patterns.js', 'usePageVisits'],
  'Switch-Case component in React': ['react-patterns.js', 'SwitchCase'],
  'Code an Todo card list': ['react-patterns.js', 'TodoCardList'],
  'Maintain timer state during page navigation': ['react-patterns.js', 'PersistentTimer']
};
